-- 코드를 입력하세요
SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) AS PRICE FROM FOOD_PRODUCT)

# SELECT *
# FROM FOOD_PRODUCT
# ORDER BY PRICE DESC
# LIMIT 1;

# SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, MAX(PRICE) AS PRICE
# FROM FOOD_PRODUCT