SELECT H.HISTORY_ID, IF(P.DISCOUNT_RATE IS NULL,
                        LENTAL_DATE * CAR.DAILY_FEE,
                        ROUND(CAR.DAILY_FEE - (CAR.DAILY_FEE * (P.DISCOUNT_RATE / 100))) * H.LENTAL_DATE) as FEE

FROM CAR_RENTAL_COMPANY_CAR as CAR,
    (SELECT CAR_ID, HISTORY_ID, TIMESTAMPDIFF(DAY,START_DATE, END_DATE) + 1 as LENTAL_DATE,
     CASE
        WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 90 THEN "90일 이상"
        WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 30 THEN "30일 이상"
        WHEN TIMESTAMPDIFF(DAY, START_DATE, END_DATE) + 1 >= 7 THEN "7일 이상"
     end as DURATION_TYPE
     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    ) as H

LEFT JOIN(
    SELECT DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) as P ON H.DURATION_TYPE = P.DURATION_TYPE

WHERE CAR.CAR_ID = H.CAR_ID and CAR.CAR_TYPE = '트럭'

ORDER BY FEE DESC, H.HISTORY_ID DESC